import React, { useState } from 'react'
import { Download, Check } from 'lucide-react'
import './ghana-additions.css'

function exportCSV(name, headers, rows) {
  const quote = value => `"${String(value ?? '').replace(/^[=+@\-\t\r]/, "'$&").replaceAll('"', '""')}"`
  const url = URL.createObjectURL(new Blob(['\uFEFF'+[headers,...rows].map(row => row.map(quote).join(',')).join('\r\n')], {type:'text/csv;charset=utf-8'}))
  const link=document.createElement('a');link.href=url;link.download=name+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
function Title({title,desc}) {return <section className="page-title"><div><h2>{title}</h2><p>{desc}</p></div></section>}
function Table({headers,children}) {return <div className="platform-table-wrap"><table className="platform-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}

export function StaffRegister({db,update}) {
  const [date,setDate]=useState(new Date().toISOString().slice(0,10)),[draft,setDraft]=useState({}),[notice,setNotice]=useState('')
  const people=db.teachers.filter(s=>s.status!=='Inactive'), saved=db.staffAttendance || []
  const value=id=>draft[id] || saved.find(r=>r.staffId===id&&r.date===date) || {status:'Unmarked',arrival:'',note:''}
  const edit=(id,key,val)=>{setDraft({...draft,[id]:{...value(id),[key]:val}});setNotice('')}
  return <div className="page-enter ghana-module"><Title title="Staff attendance" desc="Daily staff registers with arrival times and attendance notes."/><div className="module-controls"><label>Date<input aria-label="Staff attendance date" type="date" value={date} required onChange={e=>{if(e.target.value){setDate(e.target.value);setDraft({});setNotice('')}}}/></label><button className="primary" disabled={!Object.keys(draft).length} onClick={()=>{update(d=>({...d,staffAttendance:[...(d.staffAttendance||[]).filter(r=>!(r.date===date&&draft[r.staffId])),...Object.entries(draft).map(([staffId,r])=>({...r,id:crypto.randomUUID(),staffId,date}))]}),'Saved staff attendance');setDraft({});setNotice('Staff register saved.')}}><Check size={16}/> Save staff register</button><button onClick={()=>exportCSV('staff-attendance-'+date,['Date','Staff','Status','Arrival','Note'],people.map(s=>[date,s.name,value(s.id).status,value(s.id).arrival,value(s.id).note]))}><Download size={16}/> Export register</button></div><Table headers={['Staff member','Status','Arrival','Note']}>{people.map(s=><tr key={s.id}><td>{s.name}</td><td><select aria-label={`Staff attendance for ${s.name}`} value={value(s.id).status} onChange={e=>edit(s.id,'status',e.target.value)}>{['Unmarked','Present','Absent','Late','Half-day','On leave'].map(v=><option key={v}>{v}</option>)}</select></td><td><input aria-label={`Arrival for ${s.name}`} type="time" value={value(s.id).arrival} onChange={e=>edit(s.id,'arrival',e.target.value)}/></td><td><input aria-label={`Attendance note for ${s.name}`} maxLength={240} value={value(s.id).note} onChange={e=>edit(s.id,'note',e.target.value)}/></td></tr>)}</Table><p role="status" className="module-note">{notice || (Object.keys(draft).length?'You have unsaved changes.':'Unmarked staff are not assumed present.')}</p></div>
}

export function ProgressReports({db,update,rows,readOnly}) {
  const [subject,setSubject]=useState('Mathematics'),[group,setGroup]=useState('All'),[notice,setNotice]=useState('')
  const weight=Number(db.settings.sbaWeight ?? 30), period=db.settings.period+' · '+db.settings.year
  const data=db.progressScores || {}, list=rows.filter(s=>group==='All'||s.group===group)
  const key=id=>`${period}:${subject}:${id}`
  const total=s=>{const m=data[key(s.id)];return m?.sba!==undefined&&m?.exam!==undefined?Math.round((m.sba*weight/100+m.exam*(100-weight)/100)*10)/10:null}
  function score(s,part,val) {if(val!==''&&(!Number.isFinite(Number(val))||Number(val)<0||Number(val)>100)) return;update(d=>{const next={...(d.progressScores?.[key(s.id)] || {})};if(val==='')delete next[part];else next[part]=Number(val);return {...d,progressScores:{...(d.progressScores||{}),[key(s.id)]:next}}},'Updated progress scores');setNotice('Progress scores updated. Check the workspace save status.')}
  const outcome=n=>n===null?'Awaiting marks':n>=Number(db.settings.passMark)?'Meets pass threshold':'Needs support'
  return <div className="page-enter ghana-module"><Title title="SBA & progress reports" desc={`School-based assessment and examinations · ${period}`}/><div className="module-controls"><label>Class<select value={group} onChange={e=>setGroup(e.target.value)}><option>All</option>{[...new Set(rows.map(s=>s.group))].map(g=><option key={g}>{g}</option>)}</select></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{['Mathematics','English','Science','Social studies'].map(v=><option key={v}>{v}</option>)}</select></label><label>SBA / exam weighting<select disabled={readOnly} value={weight} onChange={e=>update(d=>({...d,settings:{...d.settings,sbaWeight:Number(e.target.value)}}),'Updated SBA weight')}>{[30,40,50].map(w=><option key={w} value={w}>{w}% / {100-w}%</option>)}</select></label><button disabled={!list.length} onClick={()=>exportCSV('student-progress',['Student','Class','Subject','Period','SBA weight (%)','SBA /100','Exam /100','Total /100','Outcome'],list.map(s=>[s.name,s.group,subject,period,weight,data[key(s.id)]?.sba ?? '',data[key(s.id)]?.exam ?? '',total(s) ?? '',outcome(total(s))]))}><Download size={16}/> Export progress</button></div><p className="module-note">Enter both components out of 100. Weighting is configurable; outcomes use the school’s pass threshold. These sample rules do not certify GES compliance.</p><Table headers={['Student','Class','SBA /100','Exam /100','Weighted total','Outcome']}>{list.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.group}</td>{['sba','exam'].map(part=><td key={part}>{readOnly?data[key(s.id)]?.[part] ?? '—':<input className="ghana-score" aria-label={`${part==='sba'?'SBA':'Exam'} score for ${s.name}`} type="number" min="0" max="100" step="0.1" value={data[key(s.id)]?.[part] ?? ''} onChange={e=>score(s,part,e.target.value)}/>}</td>)}<td>{total(s) ?? '—'}</td><td>{outcome(total(s))}</td></tr>)}</Table><p role="status" className="module-note">{notice}</p></div>
}

export function Wellbeing({db,update,rows,readOnly}) {
  const [studentId,setStudentId]=useState(rows[0]?.id || ''),[notice,setNotice]=useState('')
  const records=(db.wellbeing || []).filter(r=>rows.some(s=>s.id===r.studentId))
  function save(e){e.preventDefault();const form=new FormData(e.currentTarget);if(!form.get('note').trim()){setNotice('Enter details before saving.');return}update(d=>({...d,wellbeing:[{id:crypto.randomUUID(),studentId,type:form.get('type'),date:form.get('date'),note:form.get('note').trim(),status:'Open'},...(d.wellbeing||[])]}),'Added student welfare record');e.currentTarget.reset();setNotice('Welfare record updated. Check the workspace save status.')}
  return <div className="page-enter ghana-module"><Title title="Student wellbeing" desc="Health notes and disciplinary incidents linked to each learner."/><p className="module-note">Health notes and incident details are available to the school workspace owner. Use fictional information when exploring the public demo.</p>{!readOnly&&<section className="panel compose-panel"><form onSubmit={save}><div className="form-row"><label>Student<select value={studentId} onChange={e=>setStudentId(e.target.value)}>{rows.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Record type<select name="type"><option>Health note</option><option>Disciplinary incident</option></select></label></div><label>Date<input name="date" aria-label="Welfare record date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Details<textarea name="note" required maxLength={1000} rows={3} placeholder="Add a fictional health note or incident…"/></label><div className="compose-footer"><button className="primary" disabled={!rows.length}>Save welfare record</button></div></form><p role="status" className="module-note">{notice}</p></section>}<section className="ghana-section"><Table headers={['Student','Type','Date','Details','Status']}>{records.map(r=><tr key={r.id}><td>{rows.find(s=>s.id===r.studentId)?.name}</td><td>{r.type}</td><td>{r.date}</td><td>{r.note}</td><td>{readOnly?r.status:<select aria-label={`Status of welfare record ${r.id}`} value={r.status} onChange={e=>update(d=>({...d,wellbeing:d.wellbeing.map(item=>item.id===r.id?{...item,status:e.target.value}:item)}),'Updated welfare record status')}><option>Open</option><option>Resolved</option></select>}</td></tr>)}</Table>{!records.length&&<p className="module-note">No welfare records yet.</p>}</section></div>
}

export function Arrears({db,update,rows,readOnly}) {
  const [notice,setNotice]=useState('')
  const amount=n=>new Intl.NumberFormat('en-GH',{style:'currency',currency:db.settings.currency}).format(n)
  const balances=db.invoices.filter(i=>rows.some(s=>s.name===i.student)).map(i=>({...i,balance:Number(i.amount)-db.payments.filter(p=>p.invoice===i.id).reduce((n,p)=>n+Number(p.amount),0)})).filter(i=>i.balance>0)
  function reminder(){const body=balances.map(i=>`${i.student}: ${i.description}, balance ${amount(i.balance)}, due ${i.due}.`).join('\n');update(d=>({...d,messages:[{id:crypto.randomUUID(),channel:'SMS',recipient:'Outstanding fees',body:'Fee reminder draft for individual review:\n'+body,status:'Draft',date:new Date().toISOString(),author:'Finance'},...d.messages]}),'Prepared arrears reminder draft');setNotice('Draft saved in Communications for individual review. Nothing has been sent.')}
  return <div className="ghana-section"><h3>Outstanding fee follow-up</h3><p className="module-note">{balances.length} unpaid or partially paid bills. Export for review or prepare an internal draft. Review each family’s details individually before delivery.</p><div className="module-controls"><button disabled={!balances.length} onClick={()=>exportCSV('outstanding-fees',['Invoice','Student','Guardian','Due','Balance','Currency'],balances.map(i=>[i.id,i.student,rows.find(s=>s.name===i.student)?.guardian,i.due,i.balance,db.settings.currency]))}><Download size={16}/> Export arrears</button>{!readOnly&&<button disabled={!balances.length} onClick={reminder}>Prepare reminder draft</button>}</div><Table headers={['Student','Due date','Balance']}>{balances.map(i=><tr key={i.id}><td>{i.student}</td><td>{i.due}</td><td>{amount(i.balance)}</td></tr>)}</Table><p role="status" className="module-note">{notice}</p><h3>Payment receipts</h3><Table headers={['Student','Date','Amount','Receipt']}>{db.payments.filter(p=>db.invoices.some(i=>i.id===p.invoice&&rows.some(s=>s.name===i.student))).map(p=>{const invoice=db.invoices.find(i=>i.id===p.invoice);return <tr key={p.id}><td>{invoice.student}</td><td>{p.date}</td><td>{amount(Number(p.amount))}</td><td><button className="text-action" aria-label={`Download receipt for ${invoice.student}`} onClick={()=>exportCSV('receipt-'+p.id,['Receipt ID','School','Student','Invoice','Date','Method','Reference','Amount','Currency','Type'],[[p.id,db.settings.name,invoice.student,p.invoice,p.date,p.method,p.reference,p.amount,db.settings.currency,'Demo payment record']])}>Download receipt</button></td></tr>})}</Table></div>
}

