const field=(label,{required=false,type='text',aliases=[],values,defaultValue}={})=>({label,required,type,aliases,values,defaultValue})
const common={id:field('Record ID',{aliases:['id','record id']}),name:field('Full name',{required:true,aliases:['name','full name','student name','learner name','staff name','teacher name','parent name']}),email:field('Email',{aliases:['email address','e-mail']}),phone:field('Phone',{aliases:['phone number','telephone','mobile','contact number']})}
const date=field('Date',{required:true,type:'date',aliases:['date','record date']})
const student=field('Student name',{aliases:['student','student name','learner','learner name']})
const studentId=field('Student ID',{aliases:['student id','admission number','learner id']})
export const importSchemas={
  students:{label:'Students',module:'students',names:['student','students','learners','class register','pupils'],fields:{...common,id:field('Student ID',{aliases:['student id','admission number','learner id','id']}),group:field('Class / programme',{required:true,aliases:['class','grade','class name','programme','program','group','form']}),guardian:field('Guardian',{aliases:['guardian','guardian name','parent','parent guardian','parent name']}),status:field('Enrolment status',{values:['Active','Inactive','Graduated','Alumni','Withdrawn'],defaultValue:'Active',aliases:['status','enrolment status']})}},
  teachers:{label:'Staff & teachers',module:'teachers',names:['teachers','staff','employees'],fields:{...common,name:field('Full name',{required:true,aliases:['name','full name','staff name','teacher name','employee name']}),id:field('Staff ID',{aliases:['staff id','teacher id','employee id','id']}),subject:field('Subject / department',{aliases:['subject','department','subject department']}),role:field('Staff role',{values:['Teacher','Administrator','Support staff'],defaultValue:'Teacher',aliases:['staff role','job role','role']}),status:field('Staff status',{values:['Active','On leave','Inactive'],defaultValue:'Active',aliases:['status','staff status']})}},
  parents:{label:'Parents & guardians',module:'parents',names:['parents','guardians'],fields:{...common,name:field('Parent / guardian name',{required:true,aliases:['name','full name','parent name','guardian name']}),student,studentId,relationship:field('Relationship',{aliases:['relationship','relation']})}},
  classes:{label:'Classes & courses',module:'classes',names:['classes','courses','programmes'],fields:{id:common.id,name:field('Class / course name',{required:true,aliases:['class','class name','course','course name','programme','name']}),department:field('Department / faculty',{aliases:['department','faculty']}),teacher:field('Lead teacher',{aliases:['teacher','class teacher','lecturer','lead teacher']}),capacity:field('Capacity',{type:'number',aliases:['capacity','class capacity']}),credits:field('Credit hours',{type:'number',aliases:['credits','credit hours']})}},
  admissions:{label:'Admissions',module:'admissions',names:['admissions','applications','applicants'],fields:{...common,level:field('Requested level',{required:true,aliases:['level','requested level','requested class','programme','grade']}),guardian:field('Guardian',{aliases:['guardian','guardian name','parent name']}),status:field('Application status',{values:['Under review','Accepted','Enrolled','Rejected'],defaultValue:'Under review',aliases:['status','application status']}),date:{...date,defaultValue:'today',aliases:['application date','date']}}},
  timetable:{label:'Timetable',module:'timetable',names:['timetable','schedule','lessons'],fields:{id:common.id,subject:field('Subject',{required:true,aliases:['subject','course','lesson']}),group:field('Class',{required:true,aliases:['class','class name','grade','group','programme']}),teacher:field('Teacher',{aliases:['teacher','lecturer','staff name']}),day:field('Day',{required:true,values:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],aliases:['day','weekday']}),time:field('Start time',{required:true,type:'time',aliases:['time','start time','lesson time']}),room:field('Room',{aliases:['room','venue','location']})}},
  library:{label:'Library',module:'library',names:['library','books','catalogue'],fields:{id:common.id,title:field('Book title',{required:true,aliases:['title','book','book title']}),author:field('Author',{aliases:['author','writer']}),code:field('Catalogue code',{aliases:['code','isbn','catalogue code','book id']}),status:field('Loan status',{values:['Available','On loan','Reserved'],defaultValue:'Available',aliases:['status','loan status']}),borrower:field('Borrower',{aliases:['borrower','borrower name']})}},
  transport:{label:'Transport',module:'transport',names:['transport','buses','routes'],fields:{id:common.id,route:field('Route',{required:true,aliases:['route','route name']}),vehicle:field('Vehicle',{required:true,aliases:['vehicle','bus','vehicle number']}),driver:field('Driver',{aliases:['driver','driver name']}),capacity:field('Capacity',{type:'number',aliases:['capacity','seats']}),status:field('Status',{values:['Active','Maintenance','Inactive'],defaultValue:'Active',aliases:['status']})}},
  hostel:{label:'Hostel rooms',module:'hostel',names:['hostel','rooms','dormitories'],fields:{id:common.id,building:field('Building',{required:true,aliases:['building','hostel','house','block']}),room:field('Room',{required:true,aliases:['room','room number']}),capacity:field('Capacity',{required:true,type:'positiveInteger',aliases:['capacity','beds']}),occupants:field('Occupants',{type:'integer',defaultValue:'0',aliases:['occupants','occupied','occupancy']})}},
  invoices:{label:'Fee invoices',module:'fees',names:['invoices','bills','fees','billing'],fields:{id:field('Invoice ID',{aliases:['invoice id','invoice number','bill number','id']}),student,studentId,description:field('Fee description',{required:true,aliases:['description','fee','fee description','fee item','bill item']}),amount:field('Amount',{required:true,type:'positiveNumber',aliases:['amount','fee amount','billed amount','total']}),due:field('Due date',{required:true,type:'date',aliases:['due','due date','payment due']})}},
  payments:{label:'Payment records',module:'fees',names:['payments','receipts','collections'],fields:{id:field('Receipt ID',{aliases:['receipt id','receipt number','id']}),invoice:field('Invoice ID',{required:true,aliases:['invoice','invoice id','invoice number','bill number']}),amount:field('Amount received',{required:true,type:'positiveNumber',aliases:['amount','paid','amount paid','payment amount']}),method:field('Payment method',{required:true,values:['Cash','Bank transfer','Mobile money','Card'],aliases:['method','payment method']}),reference:field('Payment reference',{required:true,aliases:['reference','transaction id','transaction reference','payment reference']}),date:{...date,aliases:['payment date','date']}}},
  expenses:{label:'Expenses',module:'fees',names:['expenses','expenditure','costs'],fields:{id:common.id,description:field('Description',{required:true,aliases:['description','expense','expense description']}),amount:field('Amount',{required:true,type:'positiveNumber',aliases:['amount','cost','expense amount']}),category:field('Category',{values:['Payroll','Utilities','Supplies','Maintenance','Other'],defaultValue:'Other',aliases:['category','expense category']}),date:{...date,aliases:['expense date','date']}}},
  results:{label:'Assessment results',module:'results',names:['results','assessments','scores','marks'],fields:{id:common.id,student,studentId,subject:field('Subject',{required:true,aliases:['subject','course']}),assessment:field('Assessment title',{required:true,aliases:['assessment','assessment title','exam','test']}),score:field('Score',{required:true,type:'number',aliases:['score','marks','mark','obtained score']}),maximum:field('Maximum score',{required:true,type:'positiveNumber',aliases:['maximum','maximum score','max','out of','total marks']})}},
  attendance:{label:'Student attendance',module:'attendance',names:['attendance','student attendance','register'],fields:{id:common.id,student,studentId,date,status:field('Attendance status',{required:true,values:['Present','Absent','Late','Excused'],aliases:['status','attendance','attendance status']})}},
  staffAttendance:{label:'Staff attendance',module:'staff-attendance',names:['staff attendance','teacher attendance'],fields:{id:common.id,staffId:field('Staff ID',{aliases:['staff id','teacher id','employee id']}),staff:field('Staff name',{aliases:['staff','staff name','teacher','teacher name','name']}),date,status:field('Attendance status',{required:true,values:['Present','Absent','Late','Half-day','On leave'],aliases:['status','attendance status']}),arrival:field('Arrival time',{type:'time',aliases:['arrival','arrival time']}),note:field('Note',{aliases:['note','notes']})}},
}
const norm=value=>String(value??'').trim().toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ')
const idNorm=value=>String(value??'').trim().toLowerCase()
export function importTargets(role,allowed){return Object.keys(importSchemas).filter(target=>allowed.includes(importSchemas[target].module)&&(role==='Admin'||['Front desk','Receptionist'].includes(role)&&['students','parents','admissions'].includes(target)||role==='Accountant'&&['invoices','payments','expenses'].includes(target)||role==='Teacher'&&['attendance','results'].includes(target)||role==='Librarian'&&target==='library'||role==='Transport officer'&&target==='transport'||role==='Hostel manager'&&target==='hostel'))}
export function columnMapping(headers,target){const used=new Set();return Object.fromEntries(Object.entries(importSchemas[target].fields).map(([key,spec])=>{const index=headers.findIndex((h,i)=>!used.has(i)&&[key,spec.label,...spec.aliases].some(alias=>norm(alias)===norm(h)));if(index>=0)used.add(index);return [key,index>=0?index:null]}))}
export function inferImport(headers,name,targets){let best=null;for(const target of targets){const mapping=columnMapping(headers,target),spec=importSchemas[target];let score=Object.entries(mapping).reduce((n,[key,index])=>n+(index===null?0:spec.fields[key].required?3:1),0);score+=spec.names.some(alias=>norm(name).includes(norm(alias)))?8:0;if(!best||score>best.score)best={target,mapping,score}}return best&&best.score>0?best:null}
export function validateMapping(target,mapping,headers){if(!importSchemas[target])throw new Error('Choose a supported record type.');const used=new Set();for(const [field,index]of Object.entries(mapping)){if(!(field in importSchemas[target].fields))throw new Error('The column mapping contains an unsupported field.');if(index===null)continue;if(!Number.isInteger(index)||index<0||index>=headers.length)throw new Error('A mapped column is outside the file.');if(used.has(index))throw new Error('Map each source column to only one field.');used.add(index)}}
function converted(value,spec){const text=String(value??'').trim();if(!text)return spec.defaultValue==='today'?new Date().toISOString().slice(0,10):spec.defaultValue ?? ''
  if(text.length>1000)throw new Error(`${spec.label} exceeds 1,000 characters.`)
  if(spec.values){const match=spec.values.find(v=>norm(v)===norm(text));if(!match)throw new Error(`${spec.label} must be one of: ${spec.values.join(', ')}.`);return match}
  if(['number','integer','positiveNumber','positiveInteger'].includes(spec.type)){if(!/^(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$/.test(text))throw new Error(`${spec.label} must be a non-negative number.`);const number=Number(text.replaceAll(',',''));if(!Number.isFinite(number)||spec.type.startsWith('positive')&&number<=0||spec.type.endsWith('Integer')&&!Number.isInteger(number)||spec.type==='integer'&&!Number.isInteger(number))throw new Error(`${spec.label} is outside its valid range.`);return number}
  if(spec.type==='date'){if(!/^\d{4}-\d{2}-\d{2}$/.test(text)||Number.isNaN(Date.parse(text+'T00:00:00Z'))||new Date(text+'T00:00:00Z').toISOString().slice(0,10)!==text)throw new Error(`${spec.label} needs an unambiguous YYYY-MM-DD date.`)}
  if(spec.type==='time'&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(text))throw new Error(`${spec.label} needs a 24-hour HH:MM time.`)
  if(spec.label==='Email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(text))throw new Error('Email address is invalid.')
  return text
}
function resolvePerson(db,row,listKey,idKey,nameKey){const list=db[listKey]||[],id=row[idKey],name=row[nameKey];let matches=id?list.filter(s=>idNorm(s.id)===idNorm(id)):list.filter(s=>norm(s.name)===norm(name));if(matches.length!==1)throw new Error(`Link to exactly one existing ${listKey==='students'?'student':'staff member'} using its ID or full name. Import people first.`);const match=matches[0];if(id&&name&&norm(name)!==norm(match.name))throw new Error('The person ID and name refer to different records.');return match}
function naturalKey(target,row){const keys={students:['name','group'],teachers:['name','subject'],parents:['name','student'],classes:['name','department'],admissions:['name','level','date'],timetable:['subject','group','day','time'],library:row.code?['code']:['title','author'],transport:['route','vehicle'],hostel:['building','room'],invoices:['student','description','amount','due'],payments:['reference'],expenses:['description','amount','date','category'],results:['student','subject','assessment'],attendance:['studentId','date'],staffAttendance:['staffId','date']}[target];return keys.map(key=>norm(row[key])).join('|')}
export function planImport(db,table,target,mapping){validateMapping(target,mapping,table.headers);if(table.rows.length>5000)throw new Error('Import at most 5,000 rows at once.');const specs=importSchemas[target].fields,working={...db,[target]:[...(db[target]||[])]},entries=[]
  for(const source of table.rows){let record;const errors=[...(source.errors||[])];try{record=Object.fromEntries(Object.entries(specs).map(([key,spec])=>{const column=mapping[key],raw=source.rawCells?.[column],value=column==null?'':typeof raw==='number'&&['number','integer','positiveNumber','positiveInteger'].includes(spec.type)?raw:source.cells[column];return [key,converted(value,spec)]}));for(const [key,spec]of Object.entries(specs))if(spec.required&&record[key]==='')errors.push(`${spec.label} is required.`)
    if(['parents','invoices','results','attendance'].includes(target)){const person=resolvePerson(working,record,'students','studentId','student');record.student=person.name;if(target==='attendance'){record.studentId=person.id;record.name=person.name;delete record.student}else if(record.studentId==='')delete record.studentId}
    if(target==='staffAttendance'){const person=resolvePerson(working,record,'teachers','staffId','staff');record.staffId=person.id;delete record.staff}
    if(target==='payments'&&!errors.length&&working.payments.some(p=>idNorm(p.reference)===idNorm(record.reference))){entries.push({row:source.row,status:'duplicate',record,errors:['Payment reference already exists.']});continue}
    if(target==='payments'){const invoice=(working.invoices||[]).find(i=>idNorm(i.id)===idNorm(record.invoice));if(!invoice)throw new Error('Invoice ID was not found. Import invoices first.');record.invoice=invoice.id;const paid=(working.payments||[]).filter(p=>p.invoice===invoice.id).reduce((n,p)=>n+Number(p.amount),0);if(record.amount>Number(invoice.amount)-paid)throw new Error('Payment exceeds the outstanding invoice balance.')}
    if(target==='results'&&record.score>record.maximum)errors.push('Score exceeds the maximum score.')
    if(target==='hostel'&&record.occupants>record.capacity)errors.push('Occupants exceed room capacity.')
    if(target==='library'&&record.status==='On loan'&&!record.borrower)errors.push('A borrower is required for an on-loan book.')
    const hadId=!!record.id,duplicate=working[target].some(existing=>hadId&&idNorm(existing.id)===idNorm(record.id)||(!hadId||['payments','attendance','staffAttendance'].includes(target))&&naturalKey(target,existing)===naturalKey(target,record));if(duplicate&&!errors.length){entries.push({row:source.row,status:'duplicate',record,errors:['Matches an existing record or another row in this file.']});continue}
    if(!errors.length){if(!record.id)delete record.id;record._importSource={file:table.file,sheet:table.name,row:source.row,aiExtracted:!!table.aiExtracted,values:Object.fromEntries(table.headers.map((h,i)=>[h,source.cells[i]??'']))};working[target].push(record)}
  }catch(error){errors.push(error.message)}entries.push({row:source.row,status:errors.length?'invalid':'ready',record,errors})}
  return {target,entries,ready:entries.filter(e=>e.status==='ready').length,duplicates:entries.filter(e=>e.status==='duplicate').length,invalid:entries.filter(e=>e.status==='invalid').length}
}
export function applyImport(db,table,target,mapping,allowedTargets){if(!allowedTargets.includes(target))throw new Error('Your role cannot import this record type.');const plan=planImport(db,table,target,mapping);if(!plan.ready)throw new Error('There are no ready records to import.');return {...db,[target]:[...(db[target]||[]),...plan.entries.filter(e=>e.status==='ready').map(e=>({...e.record,id:e.record.id||crypto.randomUUID()}))]}}
