import React, { useRef, useState } from 'react'
import { ArrowRight, ArrowUpRight, GraduationCap, LayoutDashboard, UsersRound, ClipboardCheck, CircleDollarSign, BookOpen, MessageCircleMore, Check, Menu, X, Play, ChevronDown, ShieldCheck, CalendarDays, Bell, Search } from 'lucide-react'
import './landing.css'
import {MotionHeading,useLandingMotion} from './landing-motion'
import './landing-motion.css'

const modules = [
  { icon: UsersRound, title: 'Every student. One record.', text: 'Keep enrolment, guardians and student information together in one organised place.', tag: 'Student management', page: 'students' },
  { icon: ClipboardCheck, title: 'Make every day count.', text: 'Take attendance, spot patterns and know who needs a little extra support.', tag: 'Attendance & academics', page: 'attendance' },
  { icon: CircleDollarSign, title: 'A clearer view of fees.', text: 'Track cedi-denominated bills, partial payments and arrears. Prepare guardian reminders for review.', tag: 'Fees & payments', page: 'fees' },
  { icon: BookOpen, title: 'Bring learning together.', text: 'Organise classes and combine SBA with exam scores using configurable assessment weights.', tag: 'Classes & results', page: 'progress' },
  { icon: MessageCircleMore, title: 'Keep everyone in the loop.', text: 'Prepare announcements and fee reminders for SMS, email or WhatsApp. Live delivery requires a provider.', tag: 'School communication', page: 'communications' },
  { icon: LayoutDashboard, title: 'See the bigger picture.', text: 'Turn daily activity into an overview that helps you decide what comes next.', tag: 'Insights & reporting', page: 'overview' },
  { icon: ShieldCheck, title: 'Support the whole student.', text: 'Link health notes and disciplinary incidents to learner records, and track follow-up through resolution.', tag: 'Student wellbeing', page: 'wellbeing' },
  { icon: CalendarDays, title: 'A register for your team.', text: 'Record staff attendance, arrival times and notes, with downloadable daily registers.', tag: 'Staff attendance', page: 'staff-attendance' },
  { icon: GraduationCap, title: 'Make progress visible.', text: 'Create weighted SBA and exam reports for each subject and export a clear view of learner progress.', tag: 'SBA & progress reports', page: 'progress' },
]
const steps = [
  { title: 'Meet your new school workspace.', text: 'Start with a clear overview of your school. Explore the demo dashboard and see how students, staff, attendance and fees come together.', label: 'Explore your workspace', page: 'Overview' },
  { title: 'Put your people at the centre.', text: 'Give every student a home for their records, class and guardian details. Find the information your team needs in seconds.', label: 'Explore student records', page: 'Students' },
  { title: 'Make room for better school days.', text: 'Review attendance, follow term collections and keep the daily schedule in sight. Less time piecing things together. More time moving forward.', label: 'Explore the dashboard', page: 'School overview' },
]
const faqs = [
  ['What is Schofy?', 'Schofy is a school management workspace that brings student records, staff, classes, attendance, fees and results into one place. This site includes an interactive demo with sample school data.'],
  ['Can I explore it before getting started?', 'Yes. Select “Explore demo” to open the Schofy Academy sample workspace. You can browse the overview, search student records and explore the navigation without creating an account.'],
  ['Who is Schofy designed for?', 'School administrators, leadership teams and teaching staff who want a simpler way to organise everyday school operations.'],
  ['Can I use my school’s real data here?', 'The public demo uses sample records. Sign in to create a separate private school workspace when Supabase is connected. Your school data is visible only to its owner account; team access is not enabled yet.'],
  ['How do I choose a plan?', 'Start by exploring the demo to identify the modules your school needs. Subscription pricing and live onboarding are not available in this preview.'],
]

function Brand() { return <span className="ns-brand"><span className="ns-mark"><GraduationCap size={23}/></span><span className="ns-wordmark"><strong>Schofy</strong><small>School simplified</small></span></span> }
function Preview({ compact = false, active = 'Overview' }) {
  return <div className={`ns-preview ${compact ? 'compact' : ''}`}>
    <aside className="ns-preview-side"><Brand/><small>WORKSPACE</small>{[[LayoutDashboard,'Overview'],[UsersRound,'Students'],[BookOpen,'Teachers'],[CalendarDays,'Classes'],[ClipboardCheck,'Attendance'],[CircleDollarSign,'Fees & payments']].map(([Icon,label])=><span className={label===active?'selected':''} key={label}><Icon size={14}/>{label}</span>)}<div className="ns-school"><span>NA</span><div>Schofy Academy<small>2026 academic year</small></div></div></aside>
    <div className="ns-preview-main"><div className="ns-preview-top"><span><Search size={14}/> Search your workspace...</span><div><Bell size={16}/><i>OL</i></div></div><div className="ns-preview-heading"><div><small>YOUR SCHOOL, AT A GLANCE</small><h3>Good morning, Olivia <span>✦</span></h3><p>Here’s what’s happening at your school today.</p></div><span className="ns-date">September 26, 2026 <ChevronDown size={12}/></span></div><div className="ns-demo-stats">{[['Total students','1,248','+4.2%',UsersRound],['Teaching staff','86','+2.1%',BookOpen],['Attendance','94.6%','Today',ClipboardCheck],['Fees collected','GHS 184.2k','This term',CircleDollarSign]].map(([label,value,note,Icon])=><div key={label}><span>{label}<Icon size={15}/></span><strong>{value}</strong><small>{note} <span>this term</span></small></div>)}</div><div className="ns-demo-lower"><div className="ns-demo-chart"><div><strong>Attendance overview</strong><span>Last 12 school days</span></div><div className="ns-chart"><div className="ns-axis"><span>100%</span><span>75%</span><span>50%</span></div><div className="ns-chart-bars">{[68,82,76,91,86,73,87,95,83,90,81,93].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><small>{['M','T','W','T','F'][i%5]}</small></div>)}</div></div></div><div className="ns-demo-schedule"><strong>Today’s schedule <CalendarDays size={15}/></strong>{[['08:00','Mathematics','Grade 9 · Room 12'],['10:15','Staff briefing','Faculty lounge'],['12:30','Biology practical','Grade 10 · Lab 2']].map(([time,title,sub])=><div key={time}><span>{time}</span><p><b>{title}</b><small>{sub}</small></p></div>)}</div></div><div className="ns-demo-students"><strong>Student overview <span>View all ↗</span></strong>{[['MT','Maya Thompson','Grade 9 · Orion'],['EW','Ethan Williams','Grade 8 · Aspen']].map(([initials,name,grade])=><div key={name}><i>{initials}</i><b>{name}</b><span>{grade}</span><em>Active</em></div>)}</div></div>
  </div>
}

export default function LandingPage({ openPlatform }) {
  const [menu, setMenu] = useState(false)
  const [step, setStep] = useState(0)
  const [faq, setFaq] = useState(0)
  const route = window.location.pathname.replace(/\/+$/, '') || '/'
  const motionRoot=useRef(null)
  useLandingMotion(motionRoot,route)
  const home = route === '/'
  const pages = {
    '/features': ['Features', 'One connected workspace. Every school essential.', 'Explore the tools that bring your school’s daily operations together.'],
    '/how-it-works': ['How it works', 'A simpler school day starts here.', 'Get to know Schofy, from your first look to your daily workflow.'],
    '/for-schools': ['For schools', 'Built around your school. And your people.', 'A shared workspace for administrators, teachers and school leaders.'],
    '/faq': ['FAQs', 'Your questions, answered.', 'Everything to know before exploring your Schofy workspace.']
  }
  const pageInfo = pages[route]
  document.title = `${home ? 'School simplified' : pageInfo?.[0] || 'Page not found'} | Schofy`
  const go = id => window.location.assign('/' + id)
  return <div ref={motionRoot} className="ns-landing" id="top">
    <header className="ns-nav"><a href="/" aria-label="Schofy home"><Brand/></a><nav className={menu?'is-open':''} aria-label="Main navigation"><a href="/" aria-current={home?'page':undefined}>Home</a><a href="/features" aria-current={route==='/features'?'page':undefined} onClick={()=>setMenu(false)}>Features</a><a href="/how-it-works" aria-current={route==='/how-it-works'?'page':undefined} onClick={()=>setMenu(false)}>How it works</a><a href="/for-schools" aria-current={route==='/for-schools'?'page':undefined} onClick={()=>setMenu(false)}>For schools</a><a href="/faq" aria-current={route==='/faq'?'page':undefined} onClick={()=>setMenu(false)}>FAQs</a><a className="ns-mobile-signin" href="/workspace">Sign in ↗</a></nav><a className="ns-login" href="/workspace">Sign in <ArrowUpRight size={16}/></a><button className="ns-mobile-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
    <main id="main-content">{!home && <section className="ns-page-hero"><a href="/">Home</a><span> / {pageInfo?.[0] || 'Page not found'}</span><MotionHeading as="h1">{pageInfo?.[1] || 'We could not find that page.'}</MotionHeading><p>{pageInfo?.[2] || 'Head back home to explore Schofy.'}</p>{!pageInfo && <a className="ns-button" href="/">Back to home <ArrowRight size={18}/></a>}</section>}{home && <section className="ns-hero"><div className="ns-eyebrow"><span/> A LITTLE LESS ADMIN. A LOT MORE POSSIBILITY.</div><MotionHeading as="h1">Your whole school.<br/>Working <span>in harmony.<svg viewBox="0 0 450 20" aria-hidden="true"><path d="M4 14 Q215 -4 445 10"/></svg></span></MotionHeading><p>Bring your people, processes and school day together.<br/>One simple workspace. More time for what matters.</p><div className="ns-hero-actions"><button className="ns-button" onClick={openPlatform}>Explore demo <ArrowUpRight size={19}/></button><button className="ns-text-button" onClick={()=>go('how-it-works')}><span><Play size={13} fill="currentColor"/></span> See how it works</button></div><div className="ns-hero-note"><Check size={14}/> No sign-up needed <i/> Built around your school</div><div className="ns-product-stage"><span className="ns-spark spark-one" aria-hidden="true">✳</span><span className="ns-spark spark-two" aria-hidden="true">✳</span><div className="ns-floating ns-float-attendance"><span><ClipboardCheck size={19}/></span><div><small>Every school day counts</small><strong>94.6% attendance <span>↗</span></strong></div></div><Preview/><div className="ns-floating ns-float-community"><div className="ns-avatars"><span>MT</span><span>AO</span><span>LC</span></div><div><strong>Connected, by Schofy.</strong><small>Students. Teachers. Possibilities.</small></div><span className="ns-float-check"><Check size={18}/></span></div></div></section>}
    {home && <section className="ns-support"><p>A shared space for every part of your school.</p><div>{[[GraduationCap,'School leaders'],[BookOpen,'Teachers'],[UsersRound,'Administrators'],[MessageCircleMore,'School communities']].map(([Icon,title])=><span key={title}><Icon size={25}/>{title}</span>)}</div></section>}
    {(home || route === '/features') && <section className="ns-section" id="features"><div className="ns-section-heading"><span className="ns-kicker">CONNECTED BY DESIGN</span><MotionHeading>Big on possibilities.<br/>Light on busywork.</MotionHeading><p>Everything you need to keep your school moving,<br/>beautifully connected in one workspace.</p></div><div className="ns-features">{(home ? modules.slice(0,3) : modules).map(({icon:Icon,title,text,tag,page},i)=><article key={title}><div className={`ns-feature-icon tone-${i}`}><Icon size={27} strokeWidth={1.6}/></div><small>{tag}</small><h3>{title}</h3><p>{text}</p><button onClick={()=>openPlatform(page)} aria-label={`Explore ${tag}`}>Explore feature <ArrowUpRight size={17}/></button></article>)}</div>{home && <div className="ns-page-link"><a className="ns-button" href="/features">See all features <ArrowRight size={18}/></a></div>}</section>}
    {home && <section className="ns-section ns-day-section" aria-labelledby="school-day-title"><div className="ns-section-heading"><span className="ns-kicker">FROM THE FIRST BELL TO THE LAST</span><MotionHeading id="school-day-title">A clearer rhythm for every day.</MotionHeading><p>Keep the small details connected, so the bigger picture stays clear.</p></div><div className="ns-day-grid">{[[ClipboardCheck,'01','Start with attendance','Record who is here, review absences and see the day take shape.','attendance'],[BookOpen,'02','Keep learning organised','Bring classes, timetables and student results into one school workspace.','results'],[CircleDollarSign,'03','Stay on top of fees','Review bills, record payments and follow up on outstanding balances.','fees']].map(([Icon,num,title,text,page])=><article key={num}><div className="ns-day-top"><Icon size={26}/><span>{num}</span></div><h3>{title}</h3><p>{text}</p><button onClick={()=>openPlatform(page)}>Try this workflow <ArrowUpRight size={17}/></button></article>)}</div></section>}
    {(home || route === '/for-schools') && <section className="ns-school-section" id="for-schools"><div className="ns-school-photo"><img src="/assets/hero-teacher-students.png" alt="Teacher helping students learn in a classroom" loading="lazy"/><div><span>✦</span><strong>Great school days<br/>start with connected people.</strong></div></div><div className="ns-school-copy"><span className="ns-kicker">LESS FRICTION. MORE FOCUS.</span><MotionHeading>Built for the people<br/>behind the progress.</MotionHeading><p>Schools are more than schedules and spreadsheets. Schofy brings the everyday details together, so your team can focus on helping students thrive.</p><ul><li><Check/> A clear picture of your entire school</li><li><Check/> Less switching. More getting things done.</li><li><Check/> A workspace that feels easy from day one</li></ul><button className="ns-button" onClick={openPlatform}>Meet your workspace <ArrowUpRight size={18}/></button></div></section>}
    {(home || route === '/how-it-works') && <section className="ns-section ns-workflow" id="how-it-works"><div className="ns-section-heading"><span className="ns-kicker">A SIMPLER WAY FORWARD</span><MotionHeading>From scattered to connected.</MotionHeading><p>Your school day, brought together in three simple steps.</p></div><div className="ns-tabs" role="tablist" aria-label="Explore the workflow">{['Explore your workspace','Bring your people together','Run your school day'].map((label,i)=><button role="tab" id={`step-${i}`} aria-selected={step===i} aria-controls="workflow-panel" tabIndex={step===i?0:-1} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const n=(step+(e.key==='ArrowRight'?1:2))%3;setStep(n);document.getElementById(`step-${n}`)?.focus()}}} className={step===i?'active':''} onClick={()=>setStep(i)} key={label}><span>0{i+1}</span>{label}</button>)}</div><div className="ns-workflow-panel" id="workflow-panel" role="tabpanel" aria-labelledby={`step-${step}`}><div key={step} className="ns-step-copy"><span className="ns-kicker">STEP 0{step+1}</span><h3>{steps[step].title}</h3><p>{steps[step].text}</p><button className="ns-text-button" onClick={openPlatform}>{steps[step].label}<ArrowRight size={19}/></button></div><div className="ns-step-preview"><Preview compact active={steps[step].page}/></div></div></section>}
    {(home || route === '/faq') && <section className="ns-faq ns-section" id="faq"><div><span className="ns-kicker">GOOD QUESTIONS. CLEAR ANSWERS.</span><MotionHeading>A little more<br/>clarity.</MotionHeading><p>Get to know your next school workspace.</p><button className="ns-text-button" onClick={openPlatform}>Take a look around <ArrowUpRight size={18}/></button></div><div className="ns-faq-list">{faqs.map(([q,a],i)=><article key={q}><button id={`question-${i}`} aria-expanded={faq===i} aria-controls={`answer-${i}`} onClick={()=>setFaq(faq===i?-1:i)}>{q}<span>{faq===i?'−':'+'}</span></button><div id={`answer-${i}`} role="region" aria-labelledby={`question-${i}`} hidden={faq!==i}><p>{a}</p></div></article>)}</div></section>}
    {home && <section className="ns-onboarding ns-section" aria-labelledby="onboarding-title"><div><span className="ns-kicker">YOUR SCHOOL. YOUR STARTING POINT.</span><MotionHeading id="onboarding-title">Take a look.<br/>Then make it yours.</MotionHeading><p>Explore Schofy with sample data first. When you are ready, create an account with your school and owner details to begin your private workspace.</p><a className="ns-button" href="/signup">Set up your school <ArrowRight size={18}/></a></div><ol><li><span>01</span><div><h3>Explore the demo</h3><p>Try the school tools before creating an account.</p></div></li><li><span>02</span><div><h3>Tell us about your school</h3><p>Add your school name, size and owner information.</p></div></li><li><span>03</span><div><h3>Confirm your email and begin</h3><p>Open your private workspace and start adding your school records.</p></div></li></ol></section>}
    {home && <section className="ns-discover ns-section"><a href="/how-it-works"><span className="ns-kicker">A SIMPLER WAY FORWARD</span><h3>See how it works.</h3><p>Explore the workspace, bring people together and organise your school day.</p><ArrowUpRight/></a><a href="/for-schools"><span className="ns-kicker">YOUR PEOPLE. CONNECTED.</span><h3>Made for your school.</h3><p>Find a clearer way forward for administrators, teachers and school leaders.</p><ArrowUpRight/></a><a href="/faq"><span className="ns-kicker">GOOD QUESTIONS</span><h3>A little more clarity.</h3><p>Get answers about the demo, student data and getting started.</p><ArrowUpRight/></a></section>}    <section className="ns-final"><span className="ns-final-spark" aria-hidden="true">✳</span><span className="ns-kicker">MAKE SPACE FOR WHAT MATTERS</span><MotionHeading>A better school day<br/>starts here.</MotionHeading><p>Bring it all together with Schofy.</p><button className="ns-button dark" onClick={openPlatform}>Explore the demo <ArrowUpRight size={19}/></button><small>One workspace. Your whole school.</small></section></main>
    <footer className="ns-footer"><div><a href="/"><Brand/></a><p>Connected schools.<br/>Brighter possibilities.</p></div><div><strong>Explore</strong><a href="/features">Features</a><a href="/how-it-works">How it works</a><a href="/for-schools">For schools</a></div><div><strong>Get started</strong><button onClick={openPlatform}>Explore demo ↗</button><a href="/workspace">Sign in to workspace ↗</a><a href="/faq">FAQs</a></div><div className="ns-footer-note"><ShieldCheck size={25}/><strong>A thoughtful space<br/>for school management.</strong><p>Explore with sample data.<br/>No account required.</p></div></footer><div className="ns-footer-base"><span>© {new Date().getFullYear()} Schofy.</span><span>Made for the everyday. Built for the bigger picture. <span>✦</span></span><a href="#top">Back to top ↑</a></div>
  </div>
}

