import React,{useEffect,useRef,useState} from 'react'
import {workflowsFor,policyContext} from './pomaa-workflows.mjs'
import {pomaaContext} from './pomaa-context.mjs'
import {supabase} from './supabase'

export default function PomaaTools({db,role,identity,allowed,page,live,commitImport,onPrompt,busy}){
 const [error,setError]=useState(''),[loading,setLoading]=useState(false),[source,setSource]=useState(null),[recording,setRecording]=useState(false),[notice,setNotice]=useState('')
 const recorder=useRef(null),stream=useRef(null),timer=useRef(null),mounted=useRef(true)
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop())}},[])
 const policies=policyContext(db,role),resources=(db.aiResources||[]).filter(r=>r.role===role&&allowed.includes(r.module)).slice(0,30)
 async function readFile(file,voice=false){if(!file)return;if(file.size>5*1024*1024){setError('Choose a file up to 5 MB.');return}setLoading(true);setError('');setNotice('')
  try{const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});const headers={'Content-Type':'application/json'};if(live){const {data}=await supabase.auth.getSession();if(!data.session)throw new Error('Sign in again.');headers.Authorization=`Bearer ${data.session.access_token}`}
   const r=await fetch(`/api/pomaa/${voice?'voice':'document'}`,{method:'POST',headers,body:JSON.stringify({scope:live?'live':'demo',page,file:{name:file.name,base64},...(!live?{context:pomaaContext(db,{role,learnerId:identity,allowed,page})}:{})})});const result=await r.json();if(!r.ok)throw new Error(result.error||'File could not be read.');if(!mounted.current)return;if(voice){onPrompt(result.text.slice(0,6000));setNotice('Transcript is ready in the question box. Review it before sending.')}else setSource({...result,audience:'Staff'})
  }catch(e){if(mounted.current)setError(e.message)}finally{if(mounted.current)setLoading(false)}
 }
 async function record(){setError('');if(recording){clearTimeout(timer.current);recorder.current?.stop();return}try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Recording is unavailable in this browser. Upload an audio file instead.');stream.current=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){stream.current.getTracks().forEach(t=>t.stop());return}const mime=['audio/webm','audio/mp4','audio/ogg'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw new Error('Use an audio upload in this browser.');const r=new MediaRecorder(stream.current,{mimeType:mime}),chunks=[];recorder.current=r;r.ondataavailable=e=>chunks.push(e.data);r.onstop=()=>{clearTimeout(timer.current);stream.current?.getTracks().forEach(t=>t.stop());if(!mounted.current)return;setRecording(false);const ext=mime.includes('mp4')?'m4a':mime.includes('ogg')?'ogg':'webm';readFile(new File(chunks,`voice-instructions.${ext}`,{type:mime}),true)};r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop()},60000)}catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(e.message)}}
 async function saveSource(e){e.preventDefault();if(role!=='Admin'||!source?.text.trim()||!source.title.trim())return;setLoading(true);try{await commitImport(d=>({...d,aiPolicies:[{...source,id:crypto.randomUUID(),date:new Date().toISOString()},...(d.aiPolicies||[])].slice(0,6)}),'Added reviewed Pomaa policy source');setSource(null);setNotice('Policy source saved. Pomaa can cite it in this workspace.')}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function removeSource(id){try{await commitImport(d=>({...d,aiPolicies:(d.aiPolicies||[]).filter(p=>p.id!==id)}),'Removed Pomaa policy source')}catch(e){setError(e.message)}}
 return <details className="pomaa-tools" open><summary>AI workflows & resources</summary><div className="pomaa-starters">{workflowsFor(role,allowed).map(w=><button key={w.id} disabled={busy||loading||recording} onClick={()=>onPrompt(w.prompt)}>{w.label} ↗</button>)}</div>
 <details><summary>Policy & curriculum sources ({policies.length})</summary><p>Answers cite reviewed sources. Up to six sections of 6,000 characters. Staff sources stay in staff views; choose Everyone for parent and learner access.</p>{policies.map(p=><div key={p.id}><strong>{p.title}</strong> <small>{p.audience}</small>{role==='Admin'&&<button disabled={loading} onClick={()=>removeSource(p.id)}>Remove</button>}</div>)}{role==='Admin'&&<label>Upload a school document<input type="file" disabled={busy||loading} accept=".pdf,.doc,.docx,.odt,.rtf,.txt,.md,.png,.jpg,.jpeg,.webp" onChange={e=>{readFile(e.target.files[0]);e.target.value=''}}/></label>}
 {source&&<form className="pomaa-review" onSubmit={saveSource}><h3>Review policy source</h3><label>Document title<input required maxLength={200} value={source.title} onChange={e=>setSource({...source,title:e.target.value})}/></label><label>Who can use it?<select value={source.audience} onChange={e=>setSource({...source,audience:e.target.value})}><option>Staff</option><option>Everyone</option></select></label><label>Extracted source text<textarea required maxLength={6000} rows={6} value={source.text} onChange={e=>setSource({...source,text:e.target.value})}/></label><button disabled={loading} type="submit">Save reviewed source</button><button type="button" onClick={()=>setSource(null)}>Cancel</button></form>}</details>
 <details><summary>Saved AI resources ({resources.length})</summary>{!resources.length&&<p>Review and save a lesson, quiz, comment, briefing or timetable proposal from your chat.</p>}{resources.map(r=><details key={r.id}><summary>{r.title}</summary><small>{r.date.slice(0,10)} · Reviewed draft</small><pre>{r.body}</pre><button onClick={()=>{const url=URL.createObjectURL(new Blob([r.body],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='schofy-ai-resource.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download text</button></details>)}</details>
 <details><summary>Voice instructions</summary><p>Record up to one minute or upload audio. Check the transcript before asking Pomaa.</p><button disabled={busy||loading} onClick={record}>{recording?'Stop recording':'Record instructions'}</button><label>Upload audio<input disabled={busy||loading||recording} type="file" accept="audio/*,.webm,.m4a" onChange={e=>{readFile(e.target.files[0],true);e.target.value=''}}/></label></details>
 {loading&&<p role="status">Pomaa is reading your file…</p>}{recording&&<p role="status">Recording… stops automatically after one minute.</p>}{error&&<p role="alert" className="pomaa-error">{error}</p>}{notice&&<p role="status" className="pomaa-saved">{notice}</p>}
 </details>
}
