import React,{useEffect,useMemo,useRef,useState} from 'react'
import {importTable} from './import-file.mjs'
import {imageTypes,audioTypes,extensionOf} from './import-formats.mjs'
import {readAnyImport} from './import-upload.mjs'
import {supabase} from './supabase'
import {importSchemas,columnMapping,inferImport,planImport,applyImport,importTargets} from './import-core.mjs'

export default function PomaaImport({db,role,allowed,commitImport,live,back,go}){
 const targets=importTargets(role,allowed)
 const lock=useRef(false),controller=useRef(null)
 useEffect(()=>()=>controller.current?.abort(),[])
 const [sourceFile,setSourceFile]=useState(null),[sourcePreview,setSourcePreview]=useState(null)
 useEffect(()=>{if(!sourceFile)return;const url=URL.createObjectURL(sourceFile);setSourcePreview({file:sourceFile,url});return()=>URL.revokeObjectURL(url)},[sourceFile])
 const sourceUrl=sourcePreview?.file===sourceFile?sourcePreview.url:''
 const [notes,setNotes]=useState(''),[transcript,setTranscript]=useState(''),[offset,setOffset]=useState(0)
 const [sheets,setSheets]=useState([]),[sheet,setSheet]=useState(0),[header,setHeader]=useState(0),[target,setTarget]=useState(targets[0]),[mapping,setMapping]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('')
 const preview=useMemo(()=>{if(!sheets.length)return {};try{const table=importTable(sheets[sheet],header);return {table,plan:planImport(db,table,target,mapping)}}catch(err){return {error:err.message}}},[db,sheets,sheet,header,target,mapping])
 function configure(list,index,row,nextTarget){const table=importTable(list[index],row);const guess=inferImport(table.headers,list[index].name+' '+list[index].file,targets);const chosen=nextTarget||(targets.includes(list[index].target)?list[index].target:null)||guess?.target||targets[0];setTarget(chosen);setMapping(columnMapping(table.headers,chosen));setSaved('');setOffset(0)}
 async function upload(file){if(!file||lock.current)return;lock.current=true;setBusy(true);setError('');setSaved('');setSheets([]);setSourceFile(file);setNotes('');setTranscript('');controller.current=new AbortController();try{let token;if(live){const {data}=await supabase.auth.getSession();token=data.session?.access_token}const result=await readAnyImport(file,{live,role,allowed,token,signal:controller.current.signal});configure(result.sheets,0,0);setSheet(0);setHeader(0);setSheets(result.sheets);setNotes(result.notes);setTranscript(result.transcript)}catch(err){if(err.name!=='AbortError')setError(err.message)}finally{setBusy(false);lock.current=false}}
 async function save(){if(lock.current||!preview.plan?.ready)return;lock.current=true;setBusy(true);setError('');let counts;try{await commitImport(current=>{counts=planImport(current,preview.table,target,mapping);return applyImport(current,preview.table,target,mapping,targets)},`Pomaa imported ${importSchemas[target].label} from ${preview.table.file}`);setSaved(`${counts.ready} records imported and ${live?'confirmed saved to your school database':'saved in this browser'}. ${counts.duplicates} duplicates and ${counts.invalid} invalid rows skipped.`)}catch(err){setError(err.message||'The import could not be saved.')}finally{setBusy(false);lock.current=false}}
 return <div className="pomaa-import"><button disabled={busy} onClick={back}>← Back to chat</button><h3>Let Pomaa bring your records in.</h3><p>Upload your file, review the extracted records and automatically matched columns, then import all ready rows. Existing records are never overwritten. PDF, image and audio extraction needs Pomaa’s AI connection.</p><label className="pomaa-upload" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files[0])}}>Choose a file or drop it here<input aria-label="Upload school records" type="file" disabled={busy} onChange={e=>{upload(e.target.files[0]);e.target.value=''}}/><small>Spreadsheets, PDF, Word, JPG, PNG, WebP, text and audio · up to 5 MB</small></label><small>Spreadsheets stay in your browser. PDFs, images, documents and audio are sent to OpenAI for reading or transcription. Check extracted names, numbers and dates before importing. Import students before linked fees, results or attendance.</small>
 {busy&&<p role="status">Pomaa is reading your file or saving your records…</p>}{error&&<p className="pomaa-error" role="alert">{error}</p>}{preview.error&&<p role="alert">{preview.error}</p>}
 {sourceFile&&<div className="pomaa-import-source"><strong>{sourceFile.name}</strong>{sourceUrl&&<a href={sourceUrl} download={sourceFile.name}>Download source for review</a>}{sourceUrl&&imageTypes[extensionOf(sourceFile.name)]&&<img src={sourceUrl} alt="Uploaded source document"/>}{sourceUrl&&audioTypes[extensionOf(sourceFile.name)]&&<audio controls src={sourceUrl} aria-label="Review uploaded audio"/>}</div>}
 {notes&&<p className="pomaa-import-notes">{notes}</p>}{transcript&&<details><summary>Review audio transcript</summary><p style={{whiteSpace:'pre-wrap'}}>{transcript}</p></details>}
 {!!sheets.length&&<><fieldset disabled={busy}><div className="pomaa-import-controls"><label>Worksheet<select value={sheet} onChange={e=>{const index=Number(e.target.value);try{configure(sheets,index,0);setSheet(index);setHeader(0)}catch(err){setError(err.message)}}}>{sheets.map((s,i)=><option key={i} value={i}>{s.name}</option>)}</select></label><label>Header row<input type="number" min="1" max={sheets[sheet].matrix.length} value={header+1} onChange={e=>{const row=Number(e.target.value)-1;try{configure(sheets,sheet,row,target);setHeader(row);setError('')}catch(err){setError(err.message)}}}/></label><label>Record type<select value={target} onChange={e=>configure(sheets,sheet,header,e.target.value)}>{targets.map(t=><option value={t} key={t}>{importSchemas[t].label}</option>)}</select></label></div><details><summary>Review column mapping</summary><div className="pomaa-mappings">{Object.entries(importSchemas[target].fields).map(([key,spec])=><label key={key}>{spec.label}{spec.required?' *':''}<select value={mapping[key]??''} onChange={e=>{setMapping(old=>({...old,[key]:e.target.value===''?null:Number(e.target.value)}));setSaved('')}}><option value="">{spec.defaultValue?'Use default: '+spec.defaultValue:'Not mapped'}</option>{preview.table?.headers.map((h,i)=><option key={i} value={i}>{h}</option>)}</select></label>)}</div></details></fieldset>
 {preview.plan&&<><p className="pomaa-import-counts"><strong>{preview.plan.ready} ready</strong> · {preview.plan.duplicates} duplicates · {preview.plan.invalid} need correction</p><p>Review each page of records. AI row numbers refer to the extracted table. Extra source columns are retained with each imported record.</p><div className="pomaa-import-table"><table><thead><tr><th>Row</th><th>Check</th><th>Record / corrections</th></tr></thead><tbody>{preview.plan.entries.slice(offset,offset+20).map(entry=><tr key={entry.row}><td>{entry.row}</td><td>{entry.status}</td><td>{entry.errors.length?entry.errors.join(' '):Object.entries(entry.record).filter(([k])=>k!=='_importSource').map(([k,v])=>`${importSchemas[target].fields[k]?.label||k}: ${v}`).join(' · ')}</td></tr>)}</tbody></table></div><div className="pomaa-import-pagination"><button disabled={busy||offset===0} onClick={()=>setOffset(n=>n-20)}>Previous rows</button><span>{Math.min(offset+1,preview.plan.entries.length)}–{Math.min(offset+20,preview.plan.entries.length)} of {preview.plan.entries.length}</span><button disabled={busy||offset+20>=preview.plan.entries.length} onClick={()=>setOffset(n=>n+20)}>Next rows</button></div><details><summary>Correct source values on this page</summary><p>Corrections update this preview. Check your source file when a value is uncertain.</p><div className="pomaa-import-table"><table><thead><tr><th>Row</th>{preview.table.headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{preview.table.rows.slice(offset,offset+20).map(row=><tr key={row.row}><td>{row.row}</td>{row.cells.map((value,index)=><td key={index}><input aria-label={`Row ${row.row}, ${preview.table.headers[index]}`} disabled={busy} value={String(value??'')} maxLength={1000} onChange={e=>{const v=e.target.value;setSheets(old=>old.map((s,i)=>{if(i!==sheet)return s;const matrix=s.matrix.map(r=>[...r]);const sourceIndex=row.row-(s.startRow||1);matrix[sourceIndex][index]=v;const rawMatrix=s.rawMatrix?.map(r=>[...r]);if(rawMatrix)rawMatrix[sourceIndex][index]=v;return {...s,matrix,rawMatrix}}));setSaved('')}}/></td>)}</tr>)}</tbody></table></div></details><button className="pomaa-primary" disabled={busy||!preview.plan.ready} onClick={save}>Import {preview.plan.ready} ready records</button></>}
 {saved&&<div role="status" className="pomaa-saved"><p>{saved}</p><button onClick={()=>{go(importSchemas[target].module);back()}}>View {importSchemas[target].label}</button></div>}</>}
 </div>
}
